### ISSUE TITLE
Dark Mode and Search

### ISSUE THREAD

**Issue by swetoast** [agersant/polaris-android#26]
Hi :) 

2 features im currently missing are Darkmode (less strain on the battery)
and a search window for tracks and albums

**Comment by L04DB4L4NC3R** [comment]
I've been using this app for more than a month. Gotta say it's supper fast and snappy. But what's missing is a search feature. I have thousands of songs so it's a huge hassle for me to scroll to the one I want to listen to. Addition of fuzzy searching capability on either artists or songs would be a huge boon.

**Comment by pmphfm** [comment]
@swetoast @L04DB4L4NC3R, FWIW, here is are two patches that add search capabilities to backend and to android app. With these patches, you can write searches such as 
1. title:"choti si" composer:"R.D. Burman"
2. "unforgiven" artist:metallica

I am pushing maintainer to accept these patches so that I don't have to maintain them :) Let me know if you find the patches useful.

In the pull request you can see the screenshot of android app. You can build/side-load the app and still can retain the original playstore app as I have changed the app name to run it side by side.

server patch: https://github.com/agersant/polaris/pull/146
android patch: https://github.com/pmphfm/polaris-android/commit/0a7c52a4253a4f2dac7ae8dfb5397f6cc5b51356

**Comment by agersant** [comment]
Sorry for the lack of movement on my end, I have been on an extended hiatus from hobby programming (although I did a little bit the past few days).

The server patch is high on my todo list and I'll try to get to it next time I work on the server. Approach is good and I only want to make changes to implementation details. The android change is in a more precarious position because:
- I'm focusing my effort for the Android on the Flutter rewrite more than maintaining the current client
- The current `beta` release of the current client has stability issues that look time-consuming to fix. I am hesitant to merge more changes until those are resolved.

**Comment by pmphfm** [comment]
> Sorry for the lack of movement on my end, I have been on an extended hiatus from hobby programming (although I did a little bit the past few days).
> 
Totally get it.

> The server patch is high on my todo list and I'll try to get to it next time I work on the server. Approach is good and I only want to make changes to implementation details. The android change is in a more precarious position because:
> 
>     * I'm focusing my effort for the Android on the Flutter rewrite more than maintaining the current client

Ha! I went that route too. In fact I have an unstable but working version of flutter app for polaris! I mostly went that route because I did not find vue development that exciting (and there was some duplication of efforts).

For search, I modified both android app and web app. Again when I implemented [rj-mode](https://github.com/pmphfm/polaris/commit/ec06245e2f5e74d69632988e425f9add689e2ed4) I had to modify two clients which is not fun.

>     * The current `beta` release of the current client has stability issues that look time-consuming to fix. I am hesitant to merge more changes until those are resolved.

Makes sense - especially when there are users who rely on the app.
